//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International_Web_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAddress
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public int Code { get; set; }
        public string Region { get; set; }
        public string Locale { get; set; }
        public string AddressLine0 { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
    }
}
